# Generated by Django 4.1.7 on 2023-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolpocket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
