# Generated by Django 4.1.7 on 2023-04-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolpocket_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_products',
            field=models.ManyToManyField(to='toolpocket_app.product'),
        ),
    ]
