# Generated by Django 4.1.7 on 2023-05-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolpocket_app', '0005_product_pros_and_cons'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_videos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
