# Generated by Django 4.1.7 on 2023-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolpocket_app', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
